name: Create Shortlink
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL you would like to be shortened'
        required: true
        type: string
      short-url:
        description: 'The short-url to use in the shortlink (OPTIONAL)'
        type: string
jobs:
  create-shortlink:
    name: Get OIDC Token from GCP
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
          workload_identity_provider: 'projects/300964558877/locations/global/workloadIdentityPools/actions-pool/providers/actions-provider'
          service_account: 'upload-to-knish-gcs@the-static-zone.iam.gserviceaccount.com'
    - name: Publish shortlink
      run: BASE_URL=kni.sh ./shortlink.sh ${{ github.event.inputs.url }} ${{ github.event.inputs.short-url }}
